# Generated by Django 4.2.1 on 2023-05-28 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
