# Generated by Django 4.2.1 on 2023-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(default="amazon", max_length=100),
        ),
    ]
